<script setup lang="ts">
import { DocumentAdd, UploadFilled } from '@element-plus/icons-vue'
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { createJob, processJob, uploadNovel } from '@/api/creation'
import { useAuth } from '@/composables/useAuth'
import AuthenticationRequiredState from '@/components/AuthenticationRequiredState.vue'

const router = useRouter(); const { isAuthenticated } = useAuth(); const file = ref<File>(); const novelId = ref<number>(); const protagonistName = ref(''); const targetName = ref(''); const loading = ref(false); const error = ref('')
function chooseFile(event: Event) { file.value = (event.target as HTMLInputElement).files?.[0] }
async function submitUpload() { if (!file.value || loading.value) return; if (!file.value.name.endsWith('.txt') || file.value.size > 10 * 1024 * 1024) { error.value = '请上传不超过 10MB 的 .txt 小说文件'; return }; loading.value = true; error.value = ''; try { novelId.value = await uploadNovel(file.value) } catch (e) { error.value = e instanceof Error ? e.message : '上传失败' } finally { loading.value = false } }
async function submitJob() { if (!novelId.value || !protagonistName.value.trim() || !targetName.value.trim() || loading.value) return; loading.value = true; error.value = ''; try { const jobId = await createJob(novelId.value, protagonistName.value.trim(), targetName.value.trim()); await processJob(jobId); await router.push(`/creation/jobs/${jobId}`) } catch (e) { error.value = e instanceof Error ? e.message : '任务创建失败' } finally { loading.value = false } }
</script>
<template><main class="creation"><section class="intro"><p>CREATION PIPELINE</p><h1>把小说变成可对话的角色。</h1><span>上传小说后，系统会按阶段构建角色画像、样本与反应规则。</span></section><AuthenticationRequiredState v-if="!isAuthenticated" /><section v-else class="flow"><article :class="{ done: novelId }"><b>01</b><div><h2>上传小说</h2><p>{{ novelId ? `文件已接收，小说编号 ${novelId}` : '仅支持 UTF-8 文本小说，最大 10MB。' }}</p><input v-if="!novelId" type="file" accept=".txt,text/plain" @change="chooseFile" /><button v-if="!novelId" :disabled="!file || loading" @click="submitUpload"><el-icon><UploadFilled /></el-icon>{{ loading ? '正在上传…' : '上传小说' }}</button></div></article><article :class="{ disabled: !novelId }"><b>02</b><div><h2>创建构建任务</h2><p>指定故事的主角与目标角色，后台将异步完成角色构建。</p><div class="fields"><el-input v-model="protagonistName" placeholder="主角名称" /><el-input v-model="targetName" placeholder="目标角色名称" /></div><button :disabled="!novelId || !protagonistName.trim() || !targetName.trim() || loading" @click="submitJob"><el-icon><DocumentAdd /></el-icon>{{ loading ? '正在创建…' : '创建并启动任务' }}</button></div></article><p v-if="error" class="error">{{ error }}</p></section></main></template>
<style scoped>.creation{width:min(960px,calc(100% - 48px));margin:auto;padding:70px 0 100px}.intro{max-width:620px;margin-bottom:42px}.intro p{margin:0;color:#a55d43;font:500 11px "DM Mono",monospace;letter-spacing:.14em}.intro h1{margin:10px 0;font:600 40px "Noto Serif SC",serif}.intro span{color:#748084;font-size:14px;line-height:1.8}.flow{display:grid;gap:14px}.flow article{display:grid;grid-template-columns:54px 1fr;gap:18px;padding:25px;border:1px solid #e5dfd8;border-radius:8px;background:#fff}.flow article.disabled{opacity:.52}.flow b{color:#a55d43;font:500 18px "DM Mono",monospace}.flow h2{margin:0;font:600 23px "Noto Serif SC",serif}.flow p{color:#778287;font-size:12px}.flow input{display:block;margin:13px 0}.fields{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:13px 0}.flow button{display:inline-flex;gap:5px;align-items:center;padding:9px 13px;border:0;border-radius:5px;color:#fff;background:#344b4c;cursor:pointer;font-size:12px}.flow button:disabled{opacity:.5}.error{margin:0;color:#a14d42;font-size:12px}@media(max-width:600px){.creation{width:min(100% - 30px,960px);padding-top:45px}.intro h1{font-size:32px}.fields{grid-template-columns:1fr}}</style>
