<script setup lang="ts">
import { RefreshRight } from '@element-plus/icons-vue'
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { getJobProgress, redoJob, streamJobProgress } from '@/api/creation'
import type { JobProgress } from '@/types/creation'

const props = defineProps<{ jobId: string }>(); const progress = ref<JobProgress>(); const error = ref(''); const retrying = ref(false); let controller: AbortController | undefined
const route = useRoute()
const returnTarget = computed(() => route.query.from === 'my-jobs' ? '/my-jobs' : '/creation')
const returnLabel = computed(() => route.query.from === 'my-jobs' ? '返回我的任务' : '返回创作大厅')
const stageIndex = computed(() => {
  const index = progress.value?.stages.findIndex(stage => stage.jobStage === progress.value?.currentStage) ?? -1
  return index >= 0 ? index + 1 : 0
})
function stageLabel(stage: string) { return ({ CHAPTER_SPLIT: '章节切分', PASSAGE_BUILD: 'Passage 构建', ROLE_EXAMPLE_BUILD: '角色样本构建', REACTION_RULE_BUILD: '反应规则构建', ROLE_PROFILE_BUILD: '角色画像构建' })[stage] ?? stage }
function hasItemProgress(stage: JobProgress['stages'][number]) { return stage.stageMode === 'COUNTED' && stage.totalItems !== null && stage.totalItems >= 0 }
function completedItems(stage: JobProgress['stages'][number]) { return stage.successItems + stage.failedItems }
function progressPercent(stage: JobProgress['stages'][number]) { return hasItemProgress(stage) && stage.totalItems ? Math.min(100, Math.round(completedItems(stage) / stage.totalItems * 100)) : 0 }
async function load() { error.value = ''; try { progress.value = await getJobProgress(props.jobId); subscribe() } catch (e) { error.value = e instanceof Error ? e.message : '任务进度暂时无法加载' } }
function subscribe() { controller?.abort(); controller = new AbortController(); void streamJobProgress(props.jobId, controller.signal, value => { progress.value = value }).catch(e => { if ((e as Error).name !== 'AbortError' && progress.value?.state === 'RUNNING') error.value = '实时进度连接已断开，可刷新页面重连。' }) }
async function retry() { retrying.value = true; try { await redoJob(Number(props.jobId)); await load() } catch (e) { error.value = e instanceof Error ? e.message : '重试未完成' } finally { retrying.value = false } }
onMounted(load); onBeforeUnmount(() => controller?.abort())
</script>
<template><main class="job-page"><RouterLink :to="returnTarget" class="back">{{ returnLabel }}</RouterLink><section v-if="error && !progress" class="state"><p>{{ error }}</p><button @click="load">重新尝试</button></section><template v-else-if="progress"><header><p>BUILD JOB · {{ progress.jobId }}</p><h1>{{ progress.state === 'DONE' ? '角色构建完成' : progress.state === 'FAILED' ? '构建需要处理' : '角色正在构建' }}</h1><span v-if="progress.state !== 'DONE' && stageIndex">当前为第 {{ stageIndex }} / {{ progress.stages.length }} 阶段：{{ stageLabel(progress.currentStage) }}</span></header><p v-if="error" class="notice">{{ error }}</p><section class="stages"><article v-for="stage in progress.stages" :key="stage.jobStage" :class="stage.state.toLowerCase()"><div><b>{{ stageLabel(stage.jobStage) }}</b><p>{{ stage.message }}</p><div v-if="hasItemProgress(stage)" class="item-progress"><div><i :style="{ width: `${progressPercent(stage)}%` }"></i></div><small>{{ completedItems(stage) }} / {{ stage.totalItems }} · 成功 {{ stage.successItems }}<template v-if="stage.failedItems"> · 失败 {{ stage.failedItems }}</template></small></div></div><span>{{ stage.state }}</span></article></section><div v-if="progress.state === 'FAILED'" class="retry"><p>任务失败后可从可恢复阶段重新执行。</p><button :disabled="retrying" @click="retry"><el-icon><RefreshRight /></el-icon>{{ retrying ? '正在重试…' : '重试任务' }}</button></div><RouterLink v-if="progress.state === 'DONE'" class="hall" to="/">前往角色大厅</RouterLink></template></main></template>
<style scoped>.job-page{width:min(860px,calc(100% - 48px));margin:auto;padding:45px 0 100px}.back{color:#687579;font-size:13px}header{margin:35px 0 24px;padding:28px;border:1px solid #e4dfd8;border-radius:8px;background:#f8f4ef}header p{margin:0;color:#a55d43;font:500 10px "DM Mono",monospace}header h1{margin:8px 0;font:600 35px "Noto Serif SC",serif}header span{color:#788488;font-size:12px}.stages{display:grid;gap:8px}.stages article{display:grid;grid-template-columns:1fr auto;gap:6px;padding:15px;border-left:3px solid #d9d5cf;background:#fff}.stages article.running{border-color:#b47258}.stages article.done{border-color:#5f8b7f}.stages article.failed{border-color:#b65e50}.stages b{display:block;font:600 16px "Noto Serif SC",serif}.stages small,.stages p{color:#7d898c;font-size:11px}.stages p{margin:5px 0 0}.stages span{font:500 10px "DM Mono",monospace}.item-progress{margin-top:10px}.item-progress div{width:260px;max-width:100%;height:5px;overflow:hidden;border-radius:99px;background:#ebe6df}.item-progress i{display:block;height:100%;border-radius:inherit;background:#6b8c83;transition:width .2s ease}.item-progress small{display:block;margin-top:5px;font:500 10px "DM Mono","Source Han Sans CN",sans-serif;color:#7a8586}.retry,.state{margin-top:18px;padding:18px;border:1px dashed #d9d2c9;border-radius:8px}.retry button,.state button{display:inline-flex;gap:5px;align-items:center;padding:8px 12px;border:0;border-radius:5px;color:#fff;background:#344b4c;cursor:pointer}.notice{color:#a14d42;font-size:12px}.hall{display:inline-block;margin-top:20px;color:#9b5e46;font-size:13px}</style>
