<script setup lang="ts">
import { ArrowRight, Clock, Message } from '@element-plus/icons-vue'
import { onMounted, ref } from 'vue'
import { AuthenticationRequiredError, hasAccessToken } from '@/api/http'
import { listChatSessions } from '@/api/chat'
import { getPublicRolePreview } from '@/api/roles'
import AuthenticationRequiredState from '@/components/AuthenticationRequiredState.vue'
import type { ChatSessionSummary } from '@/types/chat'

const sessions = ref<ChatSessionSummary[]>([]); const names = ref<Record<number, { characterName: string; novelName: string }>>({}); const loading = ref(false); const error = ref(''); const requiresLogin = ref(!hasAccessToken())
function formatTime(value: string | null) { return value ? new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '刚刚创建' }
async function load() { if (requiresLogin.value) return; loading.value = true; error.value = ''; try { sessions.value = await listChatSessions(); const details = await Promise.all(sessions.value.map(async session => { const role = await getPublicRolePreview(session.characterId); return [session.characterId, { characterName: role.characterName, novelName: role.novelName }] as const })); names.value = Object.fromEntries(details) } catch (reason) { if (reason instanceof AuthenticationRequiredError) requiresLogin.value = true; else error.value = reason instanceof Error ? reason.message : '聊天会话暂时无法加载' } finally { loading.value = false } }
function label(session: ChatSessionSummary) { return names.value[session.characterId]?.characterName ?? `角色 ${session.characterId}` }
function novel(session: ChatSessionSummary) { return names.value[session.characterId]?.novelName ?? '原作角色' }
onMounted(() => void load())
</script>
<template><main class="chats-page"><section class="intro"><p class="eyebrow">MY CONVERSATIONS</p><h1>我正在延续的对话。</h1><p>从已有会话回到角色身边。新的对话可在角色大厅或个人角色中创建。</p></section><AuthenticationRequiredState v-if="requiresLogin" /><section v-else v-loading="loading"><div v-if="error" class="state"><p>{{ error }}</p><button @click="load">重新加载</button></div><div v-else-if="!loading && sessions.length === 0" class="state"><el-icon><Message /></el-icon><h2>还没有聊天会话。</h2><RouterLink to="/">去角色大厅开始对话</RouterLink></div><div v-else class="session-list"><RouterLink v-for="session in sessions" :key="session.sessionId" class="session-card" :to="{ path: `/chat/${session.sessionId}`, query: { characterId: session.characterId } }"><div class="mark">{{ label(session).slice(0, 1) }}</div><div><p>《{{ novel(session) }}》</p><h2>{{ label(session) }}</h2><em>{{ session.lastMessagePreview || '新的对话，等待你的第一句话。' }}</em><span><el-icon><Clock /></el-icon>{{ formatTime(session.updateTime) }}</span></div><small>{{ session.userRoleVersionId ? '个人版本会话' : '公共角色基线' }}</small><el-icon class="arrow"><ArrowRight /></el-icon></RouterLink></div></section></main></template>
<style scoped>.chats-page{width:min(1000px,calc(100% - 48px));margin:auto;padding:75px 0 100px}.intro{max-width:630px;margin-bottom:35px}.eyebrow,.session-card p{margin:0;color:#a55d43;font:500 11px "DM Mono",monospace;letter-spacing:.14em}.intro h1,.state h2{margin:8px 0;font:600 38px "Noto Serif SC",serif}.intro>p:last-child{color:#737e82;font-size:14px;line-height:1.8}.session-list{display:grid;gap:11px}.session-card{display:grid;grid-template-columns:62px minmax(0,1fr) auto auto;gap:16px;align-items:center;padding:14px;border:1px solid #e8e3dc;border-radius:8px;color:inherit;background:#fff}.session-card:hover{border-color:#c8927f}.mark{display:grid;width:62px;height:62px;place-items:center;border-radius:6px;color:#fff;background:#44585a;font:600 28px "Noto Serif SC",serif}.session-card h2{margin:4px 0;font:600 20px "Noto Serif SC",serif}.session-card span{display:inline-flex;gap:4px;align-items:center;color:#7d898c;font-size:10px}.session-card small{color:#816e65;font-size:11px}.arrow{color:#9b5e46}.state{display:grid;min-height:270px;place-content:center;justify-items:center;border:1px dashed #ded7cf;border-radius:8px;color:#788286;text-align:center}.state :deep(.el-icon){font-size:30px}.state button{padding:8px 13px;border:0;border-radius:5px;color:#fff;background:#344b4c;cursor:pointer}.state a{color:#a55d43;font-size:13px}@media(max-width:600px){.chats-page{width:min(100% - 30px,1000px);padding-top:47px}.intro h1{font-size:32px}.session-card{grid-template-columns:54px minmax(0,1fr) auto}.mark{width:54px;height:54px}.session-card small{grid-column:2}.arrow{grid-column:3;grid-row:1}}</style>
