<script setup lang="ts">
import { RefreshRight } from '@element-plus/icons-vue'
import { onMounted, ref } from 'vue'
import { AuthenticationRequiredError, hasAccessToken } from '@/api/http'
import { listMyJobs, redoJob } from '@/api/creation'
import AuthenticationRequiredState from '@/components/AuthenticationRequiredState.vue'
import type { JobState, MyJob } from '@/types/creation'

const jobs = ref<MyJob[]>([]); const total = ref(0); const page = ref(1); const pageSize = ref(12); const status = ref<JobState | undefined>(); const loading = ref(false); const error = ref(''); const retryingId = ref<number>(); const requiresLogin = ref(!hasAccessToken())
const statusOptions: Array<{ label: string; value?: JobState }> = [{ label: '全部' }, { label: '进行中', value: 'RUNNING' }, { label: '失败', value: 'FAILED' }, { label: '已完成', value: 'DONE' }, { label: '等待中', value: 'PENDING' }]
function statusLabel(value: JobState) { return ({ PENDING: '等待中', RUNNING: '构建中', DONE: '已完成', FAILED: '构建失败' })[value] }
function formatTime(value: string | null) { return value ? new Intl.DateTimeFormat('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '未开始' }
async function load() { if (requiresLogin.value) return; loading.value = true; error.value = ''; try { const result = await listMyJobs(page.value, status.value); jobs.value = result.items; total.value = result.total; pageSize.value = result.size } catch (reason) { if (reason instanceof AuthenticationRequiredError) requiresLogin.value = true; else error.value = reason instanceof Error ? reason.message : '任务暂时无法加载' } finally { loading.value = false } }
async function retry(job: MyJob) { retryingId.value = job.id; try { await redoJob(job.id); await load() } catch (reason) { error.value = reason instanceof Error ? reason.message : '任务重试未提交' } finally { retryingId.value = undefined } }
function changeStatus(value?: JobState) { status.value = value; page.value = 1; void load() }
onMounted(() => void load())
</script>
<template><main class="jobs-page"><section class="intro"><p class="eyebrow">MY BUILD JOBS</p><h1>我发起的构建。</h1><p>每项构建任务独立归属于你。失败任务会保留失败阶段与原因，可从已完成的阶段继续执行。</p></section><AuthenticationRequiredState v-if="requiresLogin" /><section v-else v-loading="loading"><div class="filters"><button v-for="option in statusOptions" :key="option.label" :class="{ active: status === option.value }" @click="changeStatus(option.value)">{{ option.label }}</button></div><div v-if="error" class="state"><p>{{ error }}</p><button @click="load">重新加载</button></div><div v-else-if="!loading && jobs.length === 0" class="state"><h2>还没有符合条件的任务。</h2><RouterLink to="/creation">前往创作大厅</RouterLink></div><div v-else class="job-list"><article v-for="job in jobs" :key="job.id" class="job-card"><RouterLink class="job-main" :to="`/creation/jobs/${job.id}`"><p>《{{ job.novelName }}》</p><h2>{{ job.targetName }} <span>与 {{ job.protagonistName }}</span></h2><div><span :class="['status', job.status.toLowerCase()]">{{ statusLabel(job.status) }}</span><span>{{ job.stage }}</span><span>{{ formatTime(job.createTime) }}</span></div><small v-if="job.failureReason">{{ job.failureReason }}</small></RouterLink><button v-if="job.status === 'FAILED'" :disabled="retryingId === job.id" @click="retry(job)"><el-icon><RefreshRight /></el-icon>{{ retryingId === job.id ? '正在提交…' : '重试' }}</button></article></div><el-pagination v-if="total > pageSize" v-model:current-page="page" layout="prev, pager, next" :page-size="pageSize" :total="total" @current-change="load" /></section></main></template>
<style scoped>.jobs-page{width:min(1000px,calc(100% - 48px));margin:auto;padding:75px 0 100px}.intro{max-width:650px;margin-bottom:30px}.eyebrow,.job-main>p{margin:0;color:#a55d43;font:500 11px "DM Mono",monospace;letter-spacing:.14em}.intro h1,.state h2{margin:8px 0;font:600 38px "Noto Serif SC",serif}.intro>p:last-child{color:#737e82;font-size:14px;line-height:1.8}.filters{display:flex;gap:8px;margin-bottom:18px}.filters button{padding:6px 11px;border:1px solid #e4ddd5;border-radius:4px;color:#687478;background:#fff;cursor:pointer;font-size:12px}.filters button.active{border-color:#a55d43;color:#914f38;background:#fbf1ec}.job-list{display:grid;gap:10px}.job-card{display:flex;align-items:center;gap:18px;padding:16px 18px;border:1px solid #e8e3dc;border-radius:8px;background:#fff}.job-main{min-width:0;flex:1;color:inherit}.job-main h2{margin:5px 0;font:600 20px "Noto Serif SC",serif}.job-main h2 span{color:#7f898b;font-size:13px;font-weight:400}.job-main div{display:flex;gap:10px;align-items:center;color:#7d898c;font-size:11px}.status{padding:3px 6px;border-radius:3px;font:500 9px "DM Mono",monospace}.running{color:#9c654a;background:#f8e9df}.done{color:#3f6864;background:#e2efeb}.failed{color:#9a5147;background:#f6e4e1}.pending{color:#6f787b;background:#eeece8}.job-main small{display:block;margin-top:8px;color:#a14d42;font-size:11px}.job-card>button,.state button{display:inline-flex;gap:5px;align-items:center;padding:8px 12px;border:0;border-radius:5px;color:#fff;background:#344b4c;cursor:pointer}.state{display:grid;min-height:230px;place-content:center;justify-items:center;border:1px dashed #ded7cf;border-radius:8px;color:#788286;text-align:center}.state a{color:#a55d43;font-size:13px}@media(max-width:600px){.jobs-page{width:min(100% - 30px,1000px);padding-top:47px}.intro h1{font-size:32px}.job-card{align-items:flex-start}.job-main div{flex-wrap:wrap}}</style>
