FROM node:24-alpine AS build

WORKDIR /app

COPY web/package.json web/package-lock.json ./
RUN npm ci
COPY web ./
RUN npm run build

FROM nginx:1.29-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY deploy/nginx/local.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80
