spring:
  datasource:
    url: jdbc:mysql://132.226.116.188:3306/novel?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB

  ai:
    openai:
      api-key: ${DS_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-v4-flash
      embedding:
        api-key: ${EMBEDDING_API_KEY}
        base-url: https://aigc.x-see.cn
        options:
          model: bge-m3

mybatis-plus:
  type-aliases-package: com.wuming.novel.domain
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler


novel:
  upload:
    max-file-size: 10MB
    save-path: data/novel