spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/novel?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB

  ai:
    openai:
      api-key: ${DS_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-v4-flash
          temperature: 0.0
      embedding:
        api-key: ${EMBEDDING_API_KEY}
        base-url: https://aigc.x-see.cn
        options:
          model: bge-m3

mybatis-plus:
  type-aliases-package: com.wuming.novel.domain
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  mapper-locations: classpath*:/mapper/**/*.xml


novel:
  upload:
    max-file-size: 10MB
    save-path: data/novel
  layer:
    min-chapter-per-layer: 15
    max-chapter-per-layer: 35
    min-layer-size: 8
    max-layer-size: 30
  recall:
    threshold: 0.6
    topK: 40
  analysis:
    batch-size: 10
